import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Button } from 'rsuite';
import styles from './index.module.css'
import "./index.less"

const App = ({ category = [] }) => {
  return (
    <div className={styles.container}>
    
      <Head>
        <title>Next React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      
      <Button appearance="primary" href="https://rsuitejs.com/">
        Getting started 
      </Button>

      <div className='test'>test</div>
      <ul>
        {
          category.map(item=>{
            return <li key={item.id}><Link href='/TestSection/detailPage/[id]' as={`/TestSection/detailPage/${item.id}`}>{item.name}</Link></li>
          })
        }
      </ul>

     
      <Image src='/cute.png' width='100px' height='100px'/>
    </div>
  )
}

// // 此函数在构建时被调用
// export async function getStaticProps() {
//   // 调用外部 API 获取博文列表
//   const res = await fetch('https://.../posts')
//   const posts = await res.json()

//   // 通过返回 { props: { posts } } 对象，Blog 组件
//   // 在构建时将接收到 `posts` 参数
//   return {
//     props: {
//       posts,
//     },
//   }
// }

// This gets called on every request
export async function getServerSideProps() {
  return { 
    props: { 
      category:[0, 1, 2, 3, 4, 5].map(item => ({id: item, name: `name-prefix-${item}`}))
   } 
  }
}

export default App;

